name: Badges-Certificate

on:
  schedule:
    # Runs at 0am UTC every day
    - cron: "0 0 * * *"
  
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges-Certificates
        uses: Dr-A-Soni/Badges-Certificates@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: <username>/<username> # optional, By default, it will automatically use the repository who's executing the workflow.
          COMMIT_MESSAGE: "My commit message to update badges" # optional
          CREDLY_USER: <ami-soni.f526dd7b_credly> # optional, but default will use the same from github
          CREDLY_SORT: RECENT or POPULAR # optional, this is the two forms from credly sort, more popular or recent first, by default use RECENT
          BADGE_SIZE: the resolution to the badges images # optional, 110x110 default
          NUMBER_LAST_BADGES: the maximum last badges to show # optional, will show the 48 in the first page
      
        

